<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOw4Hxzx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOw4Hxzx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOw4Hxzx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOw4Hxzx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOw4Hxzx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ow4Hxzx',
    'container.build_id' => 'cd4766fb',
    'container.build_time' => 1601849208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOw4Hxzx');
