<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTpWZXei\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTpWZXei/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTpWZXei.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTpWZXei\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTpWZXei\App_KernelDevDebugContainer([
    'container.build_hash' => 'TpWZXei',
    'container.build_id' => 'b8954f5a',
    'container.build_time' => 1598703540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTpWZXei');
